M48
; DRILL file {KiCad 9.0.3} date 2026-04-14T17:25:19+0700
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-14T17:25:19+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X91.02Y-32.56
X96.79Y-32.55
T2
X37.663Y-102.668
X37.663Y-133.668
X112.663Y-102.668
X112.663Y-133.668
M30
